scrape_configs:
  - job_name: 'flask_app'
    static_configs:
      - targets: ['app:8000']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'node'
    static_configs:
      - targets: ['host.docker.internal:9100']  # ou 'localhost:9100' se estiver fora do container

